// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Api = require("../utils/api.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Categories = require("./categories.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Application");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (_self) {
              Curry._1(_self[/* send */3], /* Load */0);
              Api.getCategories(/* () */0).then((function (categories) {
                        return Promise.resolve(Curry._1(_self[/* send */3], /* Update */[categories]));
                      })).catch((function () {
                      return Promise.resolve(Curry._1(_self[/* send */3], /* Fail */1));
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var onSelected = function (category) {
                Api.getCategory(category).then((function (data) {
                        console.log(category, data);
                        return Promise.resolve(data);
                      }));
                return /* () */0;
              };
              var match = _self[/* state */1];
              var tmp;
              tmp = typeof match === "number" ? (
                  match === 0 ? React.createElement("div", undefined, "...") : "Loading categories..."
                ) : (
                  match.tag ? ReasonReact.element(/* None */0, /* None */0, Categories.make(match[0], onSelected, /* array */[])) : match[0]
                );
              return React.createElement("div", {
                          className: "categories"
                        }, tmp);
            }),
          /* initialState */(function () {
              return /* NotAsked */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* Failure */Block.__(0, ["Failed to load content"])]);
                } else {
                  return /* Update */Block.__(0, [/* Loading */1]);
                }
              } else {
                return /* Update */Block.__(0, [/* Success */Block.__(1, [action[0]])]);
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
