// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
"use strict";

var Data = require("./data.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");

function getCategories() {
  return fetch("https://rawgit.com/maciejsmolinski/learnings/master/README.md")
    .then(function(prim) {
      return prim.text();
    })
    .then(function(text) {
      return Promise.resolve(Curry._1(Data.extractCategories, text));
    });
}

exports.getCategories = getCategories;
/* Data Not a pure module */
