// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var extractCategories = (
    function (text) {
      return (text.match(/\[.*?\]/ig) || []).map(category => category.slice(1, -1))
    }
  );

function extractCategories$prime(text) {
  return text.split("\n").filter((function (line) {
                return (/\[.*?\]/ig).test(line);
              }));
}

exports.extractCategories = extractCategories;
exports.extractCategories$prime = extractCategories$prime;
/* extractCategories Not a pure module */
