// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var addReasonApplicationContainer = (
      function (uniqueId) {
        var container;

        if (container = document.getElementById(uniqueId)) {
          container.remove();
        }

        container = document.createElement('div');
        container.id = uniqueId;
        document.body.appendChild(container);
      }
  );

exports.addReasonApplicationContainer = addReasonApplicationContainer;
/* addReasonApplicationContainer Not a pure module */
