// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var MyAjaxLibrary = require("myAjaxLibrary");

function main() {
  console.log(23.0 - 3.33);
  console.log(3);
  console.log(10.0 / 3.0);
  console.log(/* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* [] */0
          ]
        ]
      ]);
  console.log(/* :: */[
        1,
        /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              1,
              /* :: */[
                2,
                /* :: */[
                  3,
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]);
  console.log(1);
  console.log("hello");
  var helloWorld = "你好，" + (String("世界") + "");
  console.log("\n    long string with a slash \\\\\n    ");
  console.log(helloWorld);
  Pervasives.print_char(/* "a" */97);
  var result = "value";
  Pervasives.print_string(result);
  Pervasives.print_newline(/* () */0);
  var ghi = ( 'here is a string from javascript' );
  Pervasives.print_string(ghi);
  Pervasives.print_newline(/* () */0);
  var add = (a + b);
  MyAjaxLibrary.sendQuery({
        name: "Reason"
      });
  Pervasives.print_int(Curry._2(add, 1, 2));
  return /* () */0;
}

Pervasives.print_string("Hello World");

Pervasives.print_newline(/* () */0);

exports.main = main;
/*  Not a pure module */
