// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';


var output = "Nothing";

console.log(output);

console.log("Hello, BuckleScript and Reason!");

var test = /* Nothing */0;

exports.test   = test;
exports.output = output;
/*  Not a pure module */
