// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Express = require("express");

var Express$1 = /* module */[];

Express().use((function (_, _$1, next) {
              console.log("Hello from the Middleware");
              return Curry._1(next, /* () */0);
            })).get("/", (function (_, res) {
            return res.send("Hello from the GET handler");
          })).post("/", (function (_, res) {
          return res.send("Hello from the POST handler");
        })).listen(3131);

exports.Express = Express$1;
/*  Not a pure module */
