// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var IsomorphicUnfetch = require("isomorphic-unfetch");

var url = "https://bucklescript.github.io/docs/en/interop-cheatsheet.html";

IsomorphicUnfetch(url).then((function (response) {
          return Promise.resolve(response.text());
        })).then((function (data) {
        return Promise.resolve((console.log(data), /* () */0));
      }));

exports.url = url;
/*  Not a pure module */
