// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var IsomorphicUnfetch = require("isomorphic-unfetch");

IsomorphicUnfetch("https://cdn.rawgit.com/maciejsmolinski/learnings/master/README.md").then((function (v) {
          return Promise.resolve(v.text());
        })).then((function (v) {
        return Promise.resolve((console.log(v), /* () */0));
      }));

/*  Not a pure module */
