// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';



    var fetch = this.fetch;

    if (!fetch) {
        fetch = function () {
            return Promise.resolve({
                text: () => {
                    return Promise.resolve("dummy data");
                }
            });
        };
        this.fetch = fetch;
    }

;

fetch("https://cdn.rawgit.com/maciejsmolinski/learnings/master/README.md").then((function (v) {
          return Promise.resolve(v.text());
        })).then((function (v) {
        return Promise.resolve((console.log(v), /* () */0));
      }));

/*  Not a pure module */
