// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Data = require("./utils/data.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Document = require("./utils/document.bs.js");
var Categories = require("./components/categories.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function render(categories) {
  Document.addUniqueElement("root");
  return ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Categories.make(categories, /* array */[])), "root");
}

Curry._1(Document.clear, /* () */0);

function init() {
  return fetch("https://rawgit.com/maciejsmolinski/learnings/master/README.md").then((function (prim) {
                  return prim.text();
                })).then((function (text) {
                return Promise.resolve(render(Curry._1(Data.extractCategories, text)));
              }));
}

var App = [init];

exports.App = App;
/*  Not a pure module */
