// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var clear = (
    function () {
      typeof document !== 'undefined' && document.body && (document.body.innerHTML = "");
    }
  );

var append = (
      function (content) {
        typeof document !== 'undefined' && document.body && (document.body.innerHTML = document.body.innerHTML + '<br>' + content);
      }
    );

var Dom = /* module */[
  /* clear */clear,
  /* append */append
];

var component = ReasonReact.statelessComponent("Greeting");

function make(name, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, "Hello ", React.createElement("strong", undefined, name), "!");
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Greeting = /* module */[
  /* component */component,
  /* make */make
];

function wrapper(uniqueId) {
  return Curry._1(append, "<div id=\"" + (String(uniqueId) + ("\">" + (String(uniqueId) + "</div>"))));
}

function show(position) {
  if (position) {
    return "right";
  } else {
    return "left";
  }
}

var modules = /* array */[
  /* tuple */[
    ReasonReact.element(/* None */0, /* None */0, make("User 1", /* array */[])),
    /* Left */0
  ],
  /* tuple */[
    ReasonReact.element(/* None */0, /* None */0, make("User 2", /* array */[])),
    /* Right */1
  ]
];

Curry._1(clear, /* () */0);

$$Array.map((function (param) {
        var pos = param[1];
        wrapper(pos ? "right" : "left");
        return ReactDOMRe.renderToElementWithId(param[0], pos ? "right" : "left");
      }), modules);

exports.Dom = Dom;
exports.Greeting = Greeting;
exports.wrapper = wrapper;
exports.show = show;
exports.modules = modules;
/* clear Not a pure module */
