// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var clear = (
    function () {
      typeof document !== 'undefined' && document.body && (document.body.innerHTML = "");
    }
  );

var append = (
      function (content) {
        typeof document !== 'undefined' && document.body && (document.body.innerHTML = document.body.innerHTML + content);
      }
    );

function addUniqueElement(uniqueId) {
  return Curry._1(append, "<div id=\"" + (String(uniqueId) + "\"></div>"));
}

var Dom = /* module */[
  /* clear */clear,
  /* append */append,
  /* addUniqueElement */addUniqueElement
];

var component = ReasonReact.statelessComponent("Category");

function make(name, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("span", {
                          className: "categories__item tag is-dark"
                        }, name);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Category = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Categories");

function make$1() {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "categories"
                        }, ReasonReact.element(/* None */0, /* None */0, make("Compile to JavaScript", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Product Development", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Haskell", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Functional Programming", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Finance", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Agile", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Frontend", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("JavaScript", /* array */[])), ReasonReact.element(/* None */0, /* None */0, make("Leadership", /* array */[])));
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* subscriptions */component$1[/* subscriptions */13],
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

var Categories = /* module */[
  /* component */component$1,
  /* make */make$1
];

Curry._1(clear, /* () */0);

addUniqueElement("root");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, make$1(/* array */[])), "root");

exports.Dom = Dom;
exports.Category = Category;
exports.Categories = Categories;
/* clear Not a pure module */
