// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

var Http$1 = /* module */[];

Http.createServer((function (_, res) {
          return res.end("hello world");
        })).listen(3333);

exports.Http = Http$1;
/*  Not a pure module */
